### ISSUE TITLE
  Comments are closed. appear on pages I have them turned off, why?

### ISSUE THREAD

**Issue by michaelwesolowski** [sethta/no-page-comment#3]
Comments are closed. appear on pages I have them turned off, why and how to I prevent these words from appearing?

**Comment by sethta** [comment]
**Why is "Comments are closed" or some other text displayed after I disable my comments?**
Many themes will include text to show that comments are not enabled on a post. To remove it, you would need to talk to your theme author.

From: https://wordpress.org/plugins/no-page-comment/faq/
