### ISSUE TITLE
Leave a reply box is still showing

### ISSUE THREAD

**Issue by postik** [sethta/no-page-comment#5]
Hello,

I use this plugin and it remove comment box from page.
But when I install DW question and answer plugin, the leave a reply
box is showing below the answer.

See it here:
http://www.postinger.ph/question/what-is-the-name-of-the-first-computer/

**Comment by sethta** [comment]
Looks like you figured out how to turn them off.

The default settings for each comment type (in your example: Question) can be set on the Settings > No Page Comment screen.
